In [ ]:
import matplotlib.pyplot as plt
from skimage.feature import hog
from sklearn import datasets
from mlxtend.data import loadlocal_mnist
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC

In [ ]:
images_path = '/Users/teknikelektro/Documents/MACHINE VISION /train-images.idx3-ubyte'
labels_path = '/Users/teknikelektro/Documents/MACHINE VISION /train-labels.idx1-ubyte'
train_images, train_labels = loadlocal_mnist(images_path=images_path, labels_path=labels_path)

In [ ]:
images_path = '/Users/teknikelektro/Documents/MACHINE VISION /t10k-images.idx3-ubyte'
labels_path = '//Users/teknikelektro/Documents/MACHINE VISION /t10k-labels.idx1-ubyte'
test_images, test_labels = loadlocal_mnist(images_path=images_path, labels_path=labels_path)

In [ ]:
plt.imshow(train_images[90].reshape(28,28), cmap='gray')

In [ ]:
<matplotlib.image.AxesImage at 0x29ea1afd0>

In [ ]:
train_labels[90]

In [1]:
6

6

In [ ]:
feature, hog_img = hog(train_images[0].reshape(28,28), orientations=9, pixels_per_cell=(8, 8), cells_per_block=(2,2), visualize=True, block_norm='L2')"

In [ ]:
n_dims = feature.shape[0]

In [ ]:
n_dims

In [ ]:
144

In [ ]:
n_samples = train_images.shape[0]

In [ ]:
n_samples

In [ ]:
60000

In [ ]:
X_train, y_train = datasets.make_classification(n_samples=n_samples, n_features=n_dims)

In [ ]:
X_train.shape

In [ ]:
(60000, 144)

In [ ]:
for i in range(n_samples):
    X_train[i], _ = hog(train_images[i].reshape(28,28), orientations=9, pixels_per_cell=(8, 8), cells_per_block=(2,2), visualize=True, block_norm='L2')
    y_train[i] = train_labels[i]

In [ ]:
svm = SVC()

In [ ]:
svm.fit(X_train, y_train)

In [ ]:
SVC()
In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.
On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.

In [ ]:
n_samples = test_images.shape[0]

In [ ]:
for i in range(n_samples):
    X_train[i], _ = hog(train_images[i].reshape(28,28), orientations=9, pixels_per_cell=(8, 8), cells_per_block=(2,2), visualize=True, block_norm='L2')
    y_train[i] = train_labels[i]

In [ ]:
y_pred = svm.predict(X_test)

In [ ]:
plt.imshow(test_images[20].reshape(28,28), cmap='gray')

In [ ]:
<matplotlib.image.AxesImage at 0x13793afd0>

In [ ]:
prediksi = svm.predict(X_test[20].reshape(1, n_dims))
hasil_prediksi = prediksi[0]
print(hasil_prediksi)

In [ ]:
9

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
conf_mat = confusion_matrix(y_test, y_pred)

In [ ]:
conf_mat

In [ ]:
array([[ 978,    0,    1,    0,    0,    0,    1,    0,    0,    0],
       [   0, 1127,    2,    0,    3,    0,    1,    0,    2,    0],
       [   3,    0, 1009,    5,    3,    0,    0,    8,    2,    2],
       [   2,    0,    7,  977,    0,    5,    0,    6,    7,    6],
       [   5,    2,    0,    1,  952,    0,    4,    4,    1,   13],
       [   2,    0,    1,    9,    1,  869,    2,    2,    5,    1],
       [   4,    2,    1,    0,    3,    5,  942,    0,    1,    0],
       [   0,    3,   13,    3,   10,    2,    0,  985,    2,   10],
       [   3,    3,    2,    6,    2,    2,    0,    1,  949,    6],
       [   2,    0,    0,    5,   11,    2,    0,    5,   13,  971]])

In [ ]:
from mlxtend.plotting import plot_confusion_matrix

In [ ]:
class_names = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [ ]:
fig, ax = plot_confusion_matrix(conf_mat=conf_mat, class_names=class_names)

In [ ]:
from sklearn.metrics import precision_score

In [ ]:
precision = precision_score(y_test, y_pred, average=None)

In [ ]:
precision

In [ ]:
array([0.97897898, 0.99120493, 0.97393822, 0.97117296, 0.96649746,
       0.9819209 , 0.99157895, 0.97428289, 0.96639511, 0.96233895])

In [ ]:
from sklearn.metrics import recall_score

In [ ]:
recall = recall_score(y_test, y_pred, average=None)

In [ ]:
recall

In [ ]:
array([0.99795918, 0.99295154, 0.97771318, 0.96732673, 0.9694501 ,
       0.97421525, 0.98329854, 0.95817121, 0.97433265, 0.96233895])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy = accuracy_score(y_test, y_pred)

In [ ]:
accuracy

In [ ]:
0.9759

In [ ]:
from sklearn.metrics import f1_score

In [ ]:
f1 = f1_score(y_test, y_pred, average='macro')

In [ ]:
f1

In [ ]:
0.9757815807547701